packages/awdb_forecasts/awdb_forecasts/lib/forecasts.py
If a user requests an item that doesnt exist, previously this would just fail and return a server error. Returning an empty {} is ok and will propagate to return an empty coverage collection. 
I think this is the best way given the following issue exists:
#36
=> Return nothing if everything has been filtered out

pygeoapi-deployment/Dockerfile, pygeoapi-deployment/deployment-requirements.txt, pyproject.toml, uv.lock
Optimize the docker image to build dependencies faster and group all dependencies in the uv lock file instead of having a separate deployment requirements.txt file. 
I investigated all options and uv is quickest to install the dependencies. Since it also also us to manage all the dependencies in one pyproject.toml and forgo separate requirements files / external dependencies I think it is a good solution.
Without even factoring in caching, it ends up being 159s vs 345s (time it takes to take to build the Dockerfile on the HEAD commit of master https://github.com/internetofwater/Western-Water-Datahub/commit/eb3f4735d3984bc33cf8bfb3cf4069e4cacebc15)  
```
docker buildx build -f pygeoapi-deployment/Dockerfile -t tmp-name . --no-cache
[+] Building 159.9s (12/12) FINISHED …
```
=> Optimize Dockerfile further for faster builds with better caching

docker-compose.yml, pygeoapi-deployment/Dockerfile, pygeoapi-deployment/deployment-requirements.txt, pygeoapi-deployment/pygeoapi.config.yml, pyproject.toml, uv.lock
Fixes the dockerfile so the PRISM provider can be loaded and reduces the build time. 
This is done just by getting rid of unnecessary installs which were causing binary path conflicts. I think pygeoapi via pip installs everything we need? I am not having any errors loading any of the providers. 
I am not on principle against debian deps, but if we are deploying from a container and are already using pip/uv I think it makes sense to try and use pypi for dependencies wherever we can since we don't have to worry about OS sysadmin (the main benefit of having debian packages)
PRISM provider loads without issue now; seems like there may be an implementation issue with it? Probably best for a followup PR
http://localhost:5005/collections/usgs-prism/cube?bbox=-119.7,34.3,-119.4,34.5
```
Traceback …
```
=> Cleanup Dockerfile; Fix Zarr

pygeoapi-deployment/Dockerfile
GCP Cloud build hangs because Docker BuildKit is not installed. This removes the cache
=> Remove cache step from Docker build

cloudbuild.yaml
Have caching implemented. There are more improvements that can be made probably but it reduces build time from 5 minutes down to 2.2 minutes which is nice.
I am backing up the yaml here. We don't need to necessarily deploy from github. However, I believe that google cloud stores all substitutions. So I am fairly confident that we don't need to have any sensitive directly in the yaml anywhere and thus in the future we could deploy with the cloudbuild.yaml as the source of truth
=> Backup cloud build yaml file without secrets

packages/awdb_forecasts/awdb_forecasts/awdb_forecasts.py, packages/awdb_forecasts/awdb_forecasts/lib/forecast_locations.py, packages/com/src/com/oaf_test.py, packages/noaa_rfc/src/noaa_rfc/lib/forecast.py, packages/noaa_rfc/src/noaa_rfc/lib/forecast_test.py, packages/noaa_rfc/src/noaa_rfc/noaa_rfc.py, packages/snotel/snotel/snotel.py, packages/usace/usace/lib/locations_collection.py, packages/usace/usace/usace.py
Use a table driven test for testing OAF behavior across all providers; makes sure that all providers are behaving relatively similarly. 
More tests to come in the future. Will do a similar thing for EDR
=> Better OAF testing that generalizes across providers

packages/com/src/com/edr_test.py, packages/rise/rise/lib/location.py, packages/rise/rise/rise_edr.py
Seems like rise might be changing some upstream stuff, since upon cache invalidation there appears to be a few params with no associated locations. 
i.e. https://data.usbr.gov/rise/api/location?order[id]=asc&include=catalogRecords.catalogItems&itemStructureId=1&parameterId%5B%5D=1721 returns no locations
=> Fix rise tests for param with no data

README.md, docs/mappings.md, packages/usace/usace/lib/locations_collection.py, packages/usace/usace/lib/locations_collection_test.py, packages/usace/usace/lib/param_helpers.py, packages/usace/usace/usace_edr.py, packages/usace/usace/usace_edr_test.py, packages/usace/usace/usace_test.py, pygeoapi-deployment/pygeoapi.config.yml
Add behavior to strip location data from the param when enumerating params and then readd it when you go to request data
Example: You can request the param category stage to filter this location here: (you dont need to request the direct upstream param that is messy and includes the location name in the param itself) http://localhost:5005/collections/usace-edr/locations/2796555126?f=json&datetime=2025-01-01/..&parameter-name=Stage
New param list
=> Usace param mapper

packages/rise/rise/lib/cache.py, packages/rise/rise/lib/covjson/covjson.py, packages/rise/rise/lib/location.py, packages/rise/rise/lib/location_test.py, packages/rise/rise/rise.py, packages/rise/rise/rise_edr.py, packages/rise/rise/rise_edr_test.py
The issue I am realizing with this PR is that there is no way to filter on parameters locally without doing an unreasonable number of fetches/local joins. You have to use the upstream parameter filter in the query url itself. 
If you try to curl and include parameters it doesn't fail but it also doesn't include them. So since it doesn't include them you need to fetch the catalog item, and then fetch the parameter for each one with is not feasible. 
```
curl -X 'GET' \
'https://data.usbr.gov/rise/api/location/266&include=catalogRecords.parameters' \
-H 'accept: application/vnd.api+json' | grep parameter
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1227    0  1227    0     0   3661      0 --:--:-- --:--:-- …
```
=> Revert "Optimize rise by caching more"

packages/awdb_forecasts/awdb_forecasts/lib/covjson_builder.py
Fix an issue with the covjson where we needed to apply the calendar property and have the right type for the z axis
=> Fix covjson syntax/type  error

dashboard-ui/e2e/Chart.spec.ts, dashboard-ui/e2e/Selectors.spec.ts, dashboard-ui/src/app/hooks/useReservoirData.ts, dashboard-ui/src/features/Header/Filters.tsx, dashboard-ui/src/features/Header/Selectors/Reservoir.tsx, dashboard-ui/src/features/Header/Selectors/utils.ts, dashboard-ui/src/features/Map/config.tsx, dashboard-ui/src/features/Map/consts.ts, dashboard-ui/src/features/Map/index.tsx, dashboard-ui/src/features/Map/types.ts, dashboard-ui/src/features/Map/utils.ts, dashboard-ui/src/features/Reservior/Info.tsx, dashboard-ui/src/features/Reservior/index.tsx, dashboard-ui/src/lib/main.ts
This update should be functionally identical to the [previous ](https://github.com/internetofwater/Western-Water-Datahub/pull/88) update to the dashboard. In the code, I've updated the logic to handle multiple sources for reservoir points that should hopefully make adding additional reservoir sources as simple as adding another config entry.
1. From the starting view, zoom in
2. Smaller capacity reservoirs should render in at higher zoom levels with smaller icons
3. In the controls revealed by the Filters button, the "Show Teacups" button should toggle the teacup icon on/off
4. Teacups should always show the largest capacity reservoir when there is an overlap of icons
5. Teacup rendering logic should persist when switching basemaps
6. Selecting a Reservoir on the map or in the select …
=> Feat: added reservoir config to handle multiple reservoir layers

.github/workflows/pyright.yml, docker-compose.yml, packages/resviz/pyproject.toml, packages/resviz/resviz.sh, packages/resviz/resviz/__init__.py, packages/resviz/resviz/lib.py, packages/resviz/schema.sql, pygeoapi-deployment/Dockerfile, pygeoapi-deployment/pygeoapi.config.yml, uv.lock
Switch to use native GDAL python bindings. This makes it a lot easier to upsert multiple rows in the database per one row in the CSV. At the moment we are only including the recorded value and the 30 year average.
=> Use native gdal python bindings

pygeoapi-deployment/pygeoapi.config.yml
For performance issues, unsure if we really want to use to remote file and unzip every read. Would be a good candidate to use the cache for. This layer does lack significant metadata - so the primary relationship we would be able to infer is with geometry.
=> Add DOI Unified regions layer

uv.lock
Note I can't release pgedr onto pypi until pygeoapi publishes its next version to pypi.
=> Update pgedr version

packages/resviz/resviz/lib.py, packages/resviz/schema.sql, packages/usace/docs/mappings.md
USBR wants to be able to filter by basin. Since their csv web endpoint has the huc08 for each, you can just subset the huc08 with the first 6 characters and get the huc06. The huc06 is to my understanding equivalent to basin in their use case.
Changed the schema manually; I think this is ok but unclear how the dump is being generated
=> add huc06/basin from resviz output

pygeoapi-deployment/pygeoapi.config.yml
adding 10 forecast; there is not much data for it for some reason; most forecasts show -999; checked this both in the API and shapefiles; but adding just for the sake of consistency
=> add day 10 river forecast

packages/resviz/resviz/__init__.py
Drop NaN values in resviz crawl. This will simply drop any rows that have a NaN value.
=> Drop NaN results from resviz

pygeoapi-deployment/pygeoapi.config.yml
Add a href for all edr provides in the pygeoapi config, this way I can generate an automated csv for andrew that summarizes all the parameters with their source
=> Better dataset links for provenance

hub-ui/src/features/Map/consts.ts, hub-ui/src/features/Map/sources.ts, hub-ui/src/features/Map/utils.ts, hub-ui/src/features/Panel/Filters/Location/Basin.tsx, hub-ui/src/features/Panel/Filters/Location/Region.tsx, hub-ui/src/features/Panel/Filters/Location/State.tsx, hub-ui/src/features/Panel/Panel.module.css, hub-ui/src/managers/Main.manager.ts, hub-ui/src/pages/Layout.page.tsx, hub-ui/src/stores/main/types.ts, hub-ui/src/types/region.ts
Connected geography filters to map and global state. Should now update on map and in the backing logic.
- Selected filter should render on map and map should zoom to feature
- Selecting a different filter ie (Region -> Basin) should clear the previous filter and remove the previous feature
- Clearing a filter should reset the map view
**NOTE**
- The "Update Data" button will not work with a selected geography filter, it currently posts the geography filter feature as a wkt string in a post request to "/area"
=> Feature: geography filter with map and global state integration

dashboard-ui/src/features/Map/consts.ts, pygeoapi-deployment/pygeoapi.config.yml
I believe the usace should be labelled specifically as USACE Access 2 Water since that is the name of the dataset and there are multiple USACE APIs that are worth distinguishing from.
=> Change USACE to callout access 2 water

pygeoapi-deployment/pygeoapi.config.yml, uv.lock
- Rename USACE Access2Water collection
- Bump pygeoapi w/ following changes
- Use Collection Name instead of collection id in parameter group dropdowns
- Allow `parameter-name` filter to match on common term or uri
=> Rename USACE Acces2Water collection

packages/rise/rise/rise_edr.py
Currently rise shows only features with data for both locations and items. 
My understanding is that locations shows only features with timeseries data, but items shows everything. 
This change fixes that to match my understanding
=> Change rise to drop locations without catalog items _after_ items

pygeoapi-deployment/templates/jsonld/usace-edr/collections/items/item.jsonld
USACE has some properties with special characters like \n that for some reason cause json parsing errors and thus new to just be replaced entirely
Validated this with the following command
```
docker run internetofwater/shacl_validator_grpc_py:latest generate_geoconnex_csv --oaf_items_endpoint http://host.docker.internal:5005/collections/usace-edr/items --description "US Army Corps of Engineers Access To Water API" --contact_email cloftus@lincolninst.edu --validate_shacl --geoconnex_namespace wwdh/usace
```
=> fix usace template to handle special characters

makefile, pygeoapi-deployment/Dockerfile, pygeoapi-deployment/entrypoint.sh, pygeoapi.config.yml
Previously when I implemented templating, I moved the config into the deployment directory to make the relative paths right.
However, in order for pygeoapi to hot reload properly the config must be at the root. Thus, I moved the config to root and updated some of the paths
This works both in `dev` mode and does not affect the container build with docker build
=> Fix hot reload of server in dev mode

dashboard-ui/src/features/Reservior/Chart/index.tsx
For some reason having the limit at the end of the query string causes a 400 error
=> Hotfix limit

.vscode/launch.json, packages/noaa_rfc/src/noaa_rfc/lib/forecast.py
Currently this is failing
https://api.wwdh.internetofwater.app/collections/noaa-rfc/items/DOLU1
This failure is due to 
```
File "/opt/pygeoapi/packages/noaa_rfc/src/noaa_rfc/lib/forecast.py", line 188, in _get_data
assert any([result["espid"][0] == "BTYO3" for result in results]), (
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: A station from the California basin appears to be missing"
```
This wasn't previously failing. It seems that NOAA removed a station. As such, I have removed the assertion. 
It is important to note that this may require us to recrawl NOAA since otherwise we may have stations that no longer exist.
=> Remove failing assertion in NOAA due to change in upstream API
